server:
  port: 9443
  ssl:
    key-store: classpath:server.p12
    key-store-password: Secr3t
    key-store-type: pkcs12
    key-store-alias: https

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    #org.springframework.boot.autoconfigure: DEBUG
    #org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    #reactor.netty.http.client: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          idsvr:
            client-name: Spring Boot OpenID Demo Client
            client-id: demo-client
            client-authentication-method: mutual-tls
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/idsvr"
            scope: openid
        provider:
          idsvr:
            authorizationUri: https://localhost:8443/oauth/v2/oauth-authorize
            tokenUri: https://localhost:8443/oauth/v2/oauth-token
            jwkSetUri: https://localhost:8443/oauth/v2/oauth-anonymous/jwks

custom:
  client:
    ssl:
      key-store: demo-client.p12
      key-store-password: Secr3t
      key-store-type: pkcs12
      trust-store: idsvr.p12
      trust-store-password: changeit
      trust-store-type: pkcs12