server:
  port: 8080
  ssl:
    key-store: src/main/resources/demo-client.keystore
    key-store-password: Secr3t
#       key-store-type: pkcs12
#       key-alias: tomcat
#       key-password: Secr3t

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    #org.springframework.boot.autoconfigure: DEBUG
    #org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    #reactor.netty.http.client: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          idsvr:
            client-name: Demo
            client-id: www
#             clientSecret: no-used
            client-authentication-method: mutual-tls
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/idsvr"
            scope: openid
            pkce: disable
        provider:
          idsvr:
            authorizationUri: https://localhost:8443/oauth/v2/oauth-authorization
            tokenUri: https://localhost:8443/oauth/v2/oauth-token
            jwkSetUri: https://localhost:8443/oauth/v2/oauth-anonymous/jwks

http:
  client:
    ssl:
      key-store: demo-client.keystore
      key-store-password: Secr3t
      trust-store: src/main/resources/demo-client.keystore
      trust-store-password: config-server
      trust-store-type: pkcs12
